#!/bin/python3

import AI as zappy_ai
import sys

if __name__ == "__main__":
    try:
        args = []
        if len(sys.argv) == 3:
            args.append(sys.argv[2])
            args.append(int(sys.argv[1]))
        elif len(sys.argv) == 4:
            args.append(sys.argv[3])
            args.append(int(sys.argv[2]))
            args.append(sys.argv[1])
        else:
            raise Exception("Usage: ./zappy_ai [server_addr] server_port team_name")

        zappy_ai.AI(*args).run()

    except Exception as e:
        print(e)
        sys.exit(1)
