#!/usr/bin/env python3

import AI as zappy_ai
import sys
import argparse

if __name__ == "__main__":
    try:
        args = []

        # Create an ArgumentParser object
        parser = argparse.ArgumentParser(description='zappy_ai script', add_help=False)

        # Add arguments with flags
        parser.add_argument('-p', dest='port', type=int, default=4242)
        parser.add_argument('-n', dest='team_name')
        parser.add_argument('-h', dest='server_addr', default='localhost')

        # Parse the command-line arguments
        args = parser.parse_args()

        # Access the argument values
        port = args.port
        team_name = args.team_name
        server_addr = args.server_addr

        if port <= 0 or port > 65535:
            raise Exception("Invalid port number")
        if team_name is None:
            raise Exception("Invalid team name")
        args = [team_name, port, server_addr]
        zappy_ai.AI(*args).run()


    except Exception as e:
        #print(e)
        sys.exit(1)
